name: Build and Deploy

on:
  push:
    branches: [main]

env:
  ENVIRONMENT: stage

jobs:
  docker-build:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ""
    steps:
      - uses: actions/checkout@master
      - name: Set IMAGE_TAG
        id: image-tag
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="${GITHUB_REF_NAME}.${GITHUB_RUN_ID}-${SHORT_SHA}"
          echo ${IMAGE_TAG} >> $GITHUB_OUTPUT
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          image: danielofir/${{ github.event.repository.name }}
          build_file: Dockerfile
          tag: ${{ steps.image-tag.outputs.IMAGE_TAG }}
          tag_with_latest: true
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    outputs:
      image-tag: ${{ steps.image-tag.outputs.IMAGE_TAG }}

  # mock-build:
  #   runs-on: ubuntu-latest
  #   env:
  #     IMAGE_TAG: ""
  #   steps:
  #     - uses: actions/checkout@master
  #     - name: Set IMAGE_TAG
  #       id: image-tag
  #       run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  #   outputs:
      # image-tag: ${{ steps.image-tag.outputs.IMAGE_TAG }}

  update-tag:
    runs-on: ubuntu-latest
    needs: docker-build
    # needs: mock-build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Sync charts repo
        env:
          GH_TOKEN: ${{ secrets.CHARTS_COMMITTER_TOKEN }}
        run: |
          git config --global user.email "auto@tagger.com"
          git config --global user.name "Auto Tagger"
          git clone https://${GH_TOKEN}@github.com/DanielOfir/application-charts.git          
          cd application-charts
          cd charts/${{ github.event.repository.name }}/configs/${ENVIRONMENT}
          yq -i '.deployment.image.tag = "${{ needs.docker-build.outputs.image-tag }}"' ${ENVIRONMENT}.yaml
          git add .
          git commit -m "Update tag to ${{ needs.docker-build.outputs.image-tag }}"
          git push origin main